### ISSUE TITLE
Wrong connection in schematics

### ISSUE THREAD

**Issue by Julius112** [prickle/TeensySpectrumAnalyser#2]
Hi Nick,

First of all - thanks a lot for your amazing instructions.
It's been super useful for me build my own spectrum analyser. I use a WS2812B LED strip, which is cut in pieces and stuck together in a way that it builds a matrix. As the protocol of the WS2812B chips is extremely time sensitive and doesn't like interrupts, when writing data to the LEDs, I use an Arduino Pro Mini to handle the LED output. The Arduino is connected with the Teensy via i2c.
But that's actually not the issue...
I noticed that in the checked-in schematics there is a direct connection from the RCA pin to AGND of the Teensy board. Shouldn't there be a connection from RCA shell to AGND?
Please correct me if I'm wrong...however that was the only way I could get it to work.

Cheers,
Julius

**Comment by prickle** [comment]
Hi Julius.
Thanks for your nice comments. That sounds like a clever setup you have going, I'm glad my simple setup helped you.

Now you mention it I realise the wiring diagram is a bit ambiguous. The black ground wire is meant for the outer RCA shell to AGND and the inner signal pin is for the purple wire to the bias resistor and decoupling capacitor just as you surmised.  For a proper schematic, look at the info for the ADC input component in the Teensy audio design tool. [http://www.pjrc.com/teensy/gui/](http://www.pjrc.com/teensy/gui/)

In fact it might work the other way round but not if you have a common system ground. It is a shame that the parts available in Fritzing are somewhat limited at the moment. 

Glad you got it working! You can do so much more than I did with your RGB colour and brightness  control. I would love to see it!

Cheers,
Nick.

**Comment by Julius112** [comment]
Hi Nick,

I'm pretty sure it would have been possible to do everything with the Teensy board only. However, due to my limited knowledge of interrupt handling on these boards I just used another microcontroller.

Being honest, I don't find the diagram from the GUI tool very useful as there is no mentioning of the audio ground (shell). That's why I used your diagram.

Anyway - happy to have it working now. I build the whole thing for a "portable" speaker system on a cart which we use for festivals on the campsite or on birthdays. As this thing is mostly focused on producing an unbearable amount of bass, I also had to manipulate the Teensys internal PDB to have a higher resolution on the bass frequencies. In the end it was enough to redefine a few compiler macros. I can send you a video, when the prototype is attached to the speaker, if you would like to see it.


Cheers,
Julius

**Comment by prickle** [comment]
Hi Julius. 

I think it what you have done sounds like the best way, I have used WS2812 and they don't play nice with timing. Check out [Mavpixel](https://github.com/prickle/Mavpixel) for an example. I had to break the strips into short lengths of eight pixels to get the interrupt rate high enough for full-speed serial.

I think some of the Teensy Neopixel libraries use DMA to lower interrupt overhead. But the Pro Mini is so cheap and cheerful and serve so well as glue logic or port extenders I often do the same as you and throw an extra processor or two in a project. My other go-to is a really super-cheap microcontroller purpose-designed for this kind of thing, the Texas Instruments [MSP-430](http://www.ti.com/tool/msp-exp430g2et) series chips. I have had good results with these and you can get them in DIP packages and code them Arduino-style using Energia.

I would love to see a video! Great work! Looking forward to your project's completion.

Cheers,
Nick.
